name: robo_adm_mobile_v2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # Dependências de Bluetooth
  flutter_blue: ^0.8.0  # Para BLE (Bluetooth Low Energy)
  flutter_bluetooth_serial: ^0.4.0  # Para Bluetooth clássico

  # Dependências comuns
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
