name: joystickv1
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you deseja publicar no pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue: ^0.8.0
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/fonts/
    - lib/assets/icones/

  fonts:
    - family: Montserrat
      fonts:
        - asset: lib/assets/fonts/Montserrat-Regular.ttf
        - asset: lib/assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: lib/assets/fonts/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: lib/assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: lib/assets/fonts/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: lib/assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: lib/assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: lib/assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: lib/assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: lib/assets/fonts/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: lib/assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: lib/assets/fonts/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: lib/assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: lib/assets/fonts/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic
