name: robo_adm_mobile_v2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Dependências comuns
  cupertino_icons: ^1.0.8
  logging: ^1.0.2
  permission_handler: ^11.3.1
  file_picker: ^8.1.2

  # Dependência para SQLite
  sqflite: ^2.0.0+4
  path: ^1.8.0

  # Dependência para comunicação BLE (Bluetooth Low Energy)
  flutter_blue_classic: ^0.0.3

  # Dependências adicionais
  shared_preferences: ^2.3.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
