name: robo_adm_desktop_v1
description: "A new Flutter project."
publish_to: 'none'
version: 0.2.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4
  window_manager: 0.2.4
  system_theme: ^2.3.1
  flutter_acrylic: ^1.0.0+2
  flutter_markdown: ^0.6.13
  fluent_ui: ^4.0.0 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true