name: robo_adm_desktop_v1
description: "Versão desktop para administração do robo."
publish_to: 'none'
version: 0.2.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.1.2
  flutter_acrylic: ^1.0.0+2
  flutter_libserialport: ^0.4.0
  flutter_markdown: ^0.6.13
  fluent_ui: ^4.0.0
  fpdart: ^1.0.0
  google_fonts: ^4.0.4
  path: ^1.8.0
  path_provider: ^2.0.11
  system_theme: ^2.3.1
  window_manager: 0.2.4
  libserialport: ^0.3.0+1
  flutter_map: ^7.0.2    # Para uso do mapa
  latlong2: ^0.9.1        # Para coordenadas geográficas (para o mapa)
  geolocator: ^13.0.2
  flutter_blue_plus_windows: ^1.24.22
  flutter_blue_plus: ^1.24.22
  audioplayers: ^6.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.1.6
  flutter_launcher_icons: ^0.13.1

flutter_native_splash:
  color: "#000000"
  image: lib/src/assets/trinca.png

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "lib/src/assets/trinca.png"
    icon_size: 48

flutter:
  uses-material-design: true
  assets:
    - lib/src/assets/trinca.png
