name: robo_adm_mobile_v2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # Dependências de Bluetooth
  flutter_blue: ^0.8.0  # Versão estável mais próxima e conhecida
  flutter_bluetooth_serial: ^0.4.0  # Versão estável

  # Dependências comuns
  cupertino_icons: ^1.0.8
  logging: ^1.0.2
  permission_handler: ^11.3.1
  file_picker: ^8.1.2

  # Dependência para SQLite
  sqflite: ^2.0.0+4
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
